Task/setting ts redux
CosmicTeam/react-project-kitchen-frontend pull request #75
Opened 2021-10-30 18:42 UTC by rossifumi46

2021-10-30 21:19 UTC, kaa-it requested changes

2021-10-30 21:19 UTC, kaa-it commented on src/services/commonSlice.ts
> +      window.localStorage.setItem('jwt', '');
Нужно использовать removeItem

2021-10-30 21:19 UTC, kaa-it commented on src/components/Settings/index.tsx
> +              Or click here to logout.
Нет перевода

2021-10-30 21:19 UTC, kaa-it commented on src/components/Settings/SettingsForm.tsx
> +            Update Settings
Нет перевода

2021-10-30 21:19 UTC, kaa-it commented on src/components/Settings/SettingsForm.tsx
> +              placeholder="New Password"
Нет перевода

2021-10-30 21:19 UTC, kaa-it commented on src/components/Settings/SettingsForm.tsx
> +              placeholder="Short bio about you"
Нет перевода

2021-10-30 21:19 UTC, kaa-it commented on src/components/Settings/SettingsForm.tsx
> +              placeholder="Username"
Нет перевода

2021-10-30 21:19 UTC, kaa-it commented on src/components/Settings/SettingsForm.tsx
> +              placeholder="URL of profile picture"
Нет перевода

2021-10-30 21:19 UTC, kaa-it commented on src/services/settingsSlice.ts
> +      })
Если исходить из старого кода (в reducers/common.js):
```
case SETTINGS_SAVED:
      return {
        ...state,
        redirectTo: action.error ? null : "/",
        currentUser: action.error ? null : action.payload.user,
      };
```
В случае успешного сохранения настроек, новые данные пользователя, полученные из ответа на асинхронный запрос, должны быть сохранены в поле currentUser стейта, находящегося в commonSlice и в поле redirectTo того же стейта должен быть записан роут главной страницы ("/"), что в свою очередь должно приводить к редиректу на главную страницу. У тебя всего этого не происходит. Собственно поэтому я и предлагал не создавать отдельного слайса для settings и все его редьюсеры разместить в commonSlice. Второй вариант создать специальный экшен в commonSlice, который будет обновлять состояние этого слайса, и диспатчерить его в случае успешного выполнения асинхронного запроса на сохранение данных пользователя.

2021-10-30 21:19 UTC, kaa-it commented on src/services/commonSlice.ts
> +      state.redirectTo = "/";
Редиректа на главную страницу в случае логаута все-таки не происходит, я так понимаю, что и в старом коде не происходило, так как в Settings нигде не проверяется это поле. Было бы хорошо заодно это пофиксить. Как и редирект в случае успешного сохранения данных пользователя.

2021-10-30 21:29 UTC, kaa-it commented on src/components/Settings/SettingsForm.tsx
> +const SettingsForm: FC<TSettingsFormProps> = ({ currentUser, onSubmitForm, inProgress }) => {
Нет смысла все это передавать в пропсах, если все это можно извлечь с помощью useAppSelector, а onSubmitForm просто перенести сюда из Settings

2021-10-30 21:31 UTC, kaa-it requested changes

2021-10-30 21:31 UTC, kaa-it commented on src/components/Settings/SettingsForm.tsx
> +const SettingsForm: FC<TSettingsFormProps> = ({ currentUser, onSubmitForm, inProgress }) => {
Нет смысла все это передавать в пропсах, если все это можно извлечь с помощью useAppSelector, а onSubmitForm просто перенести сюда из Settings

2021-11-01 14:40 UTC, rossifumi46 commented on src/services/commonSlice.ts
> +      state.redirectTo = "/";
работает

2021-11-01 14:44 UTC, rossifumi46 commented on src/services/commonSlice.ts
> +      state.redirectTo = "/";
работает

2021-11-01 15:18 UTC, rossifumi46 commented on src/components/Settings/SettingsForm.tsx
> +const SettingsForm: FC<TSettingsFormProps> = ({ currentUser, onSubmitForm, inProgress }) => {
я пока так оставлю

2021-11-01 16:37 UTC, merged