Create validation hook Closes #34
CosmicTeam/react-project-kitchen-frontend pull request #88
Opened 2021-11-05 18:47 UTC by ppridanov

Привет всем. Чекните. Кажется код слишком громоздкий. Может есть идеи как отрефакторить? Критика тоже приветствуется.

2021-11-06 15:07 UTC, kaa-it commented
По дизайну у сообщений об ошибках должен быть другой шрифт... Должна быть красная рамочка и иконка у полей ввода и кнопка задизейблена при наличии ошибок валидации. По коду еще посмотрю поподробнее.

2021-11-06 21:01 UTC, InInferno approved these changes

2021-11-07 15:38 UTC, kaa-it commented
При вводе имени пользователя поле ввода email уезжает вниз, хотя ошибок связанных с именем поользователя не
![Screenshot from 2021-11-07 18-36-48](https://user-images.githubusercontent.com/4102978/140651698-71bfa2d4-317d-417d-b51d-b886dcf05f8b.png)
т

2021-11-07 15:44 UTC, ppridanov commented
> При вводе имени пользователя поле ввода email уезжает вниз, хотя ошибок связанных с именем пользователя не ![Screenshot from 2021-11-07 18-36-48](https://user-images.githubusercontent.com/4102978/140651698-71bfa2d4-317d-417d-b51d-b886dcf05f8b.png) Одним словом, пустые поля для ошибок появляются даже если ошибок нет.

Done

2021-11-07 15:45 UTC, kaa-it requested changes
При вводе имени пользователя поле ввода email уезжает вниз, хотя ошибок связанных с именем пользователя не
![Screenshot from 2021-11-07 18-36-48](https://user-images.githubusercontent.com/4102978/140651698-71bfa2d4-317d-417d-b51d-b886dcf05f8b.png)
Одним словом, пустые поля для ошибок появляются даже если ошибок нет.

2021-11-07 16:21 UTC, merged